### ISSUE TITLE
help error

### ISSUE THREAD

**Issue by nlefebvre1410** [isychev/fos-routing#3]
Hello,
he me but as error
line 17 exports is not defined which is:
exports ["router"] = (window.Routing)
Thank you in advance for your assistance

**Comment by isychev** [comment]
@nlefebvre1410 Hello
fos-routing not defined in window
It's a separate library
You can use:
```js 
exports ["router"] = Routing
// or
var Routing = require('for-routing').default;
window.Routing = Routing;
exports ["router"] = window.Routing;
```

**Comment by nlefebvre1410** [comment]
Yes !! resolved:
```
let Routing = require('fos-routing')

import RoutingData from '../routing/fos_js_routes_export.js'

Routing.setData(RoutingData)
export default Routing
```
thanks you
